FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS build-env
ARG TARGETOS TARGETARCH TARGETVARIANT
RUN apk add git gcc
RUN mkdir /app
WORKDIR /app
COPY . .
RUN go mod download
RUN go mod verify
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH GOARM=${TARGETVARIANT#v} go build -ldflags="-w -s" -o wait4it
FROM alpine:3.22
LABEL org.opencontainers.image.source="https://github.com/ph4r5h4d/wait4it"
COPY --from=build-env /app/wait4it .
USER 1001
ENTRYPOINT ["./wait4it"]
